classDiagram
    %% Estilos
    classDef interfaceClass fill:#f5f5f5,stroke:#616161,stroke-width:1px,stroke-dasharray: 5 5;
    classDef implementationClass fill:#ffccbc,stroke:#bf360c,stroke-width:2px;

    class IOrdenador~T~ {
        <<interface>>
        +ordenar(datos: vector~T~&)
    }

    class OrdenadorQuick~T~ {
        -particiones: int
        -particionar(arr: vector~T~&, bajo: int, alto: int) int
        -quickSortRecursivo(arr: vector~T~&, bajo: int, alto: int)
        +ordenar(datos: vector~T~&)
    }

    IOrdenador~T~ <|.. OrdenadorQuick~T~ : Implementa

    note for OrdenadorQuick~T~ "Algoritmo O(n log n) promedio\nIn-place (sin memoria extra significativa)"

    class IOrdenador interfaceClass
    class OrdenadorQuick implementationClass
